DROP TABLE IF EXISTS requests;

CREATE TABLE IF NOT EXISTS requests (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  machine_id TEXT NOT NULL,
  issue TEXT NOT NULL,
  email TEXT,
  timestamp DATETIME DEFAULT CURRENT_TIMESTAMP);